language: node_js
node_js:
  - 4.2
install:
  - rvm install 2.1
  - gem install jekyll
  - npm install
script:
  - jekyll build
deploy:
  -
    skip_cleanup: true
    provider: script
    script: ./scripts/stage.sh
    on:
      branch: master
# notifications:
#   slack: cascadiafest:upIkrnH6MWQ3K75VTBBrFkkx