language: node_js
node_js:
  - 4.2
rvm:
  - 2.1
install: gem install bundler && bundle install
deploy:
  -
    skip_cleanup: true
    provider: script
    script: npm run stage
    on:
      branch: master
notifications:
  slack: cascadiafest:upIkrnH6MWQ3K75VTBBrFkkx