language: node_js
node_js:
  - 4.2
install:
  - rvm install 2.1
  - gem install jekyll
  - npm install
script:
  - npm run build
deploy:
  -
    skip_cleanup: true
    provider: script
    script: npm run deploy-prod
    on:
      branch: master
after_success:
  - "[[ $TRAVIS_PULL_REQUEST -ne 'false' ]] && npm run deploy-pr -- --domain pr-$TRAVIS_PULL_REQUEST.news.cascadiafest.surge.sh"
notifications:
  slack: cascadiafest:upIkrnH6MWQ3K75VTBBrFkkx
