# Site settings
title: CascadiaFEST
email: info@cascadiajs.com
description: >
  CascadiaFest is a three-day, community-driven conference on the cutting
  edge of JavaScript and CSS. Browser, server, OS – we cover it all.
baseurl: ""
url: "http://news.cascadiafest.org" # the base hostname & protocol for your site
twitter_username: cascadiajs
github_username:  cascadiajs

permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

exclude:
  - node_modules
  - package.json
