# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CascadiaFEST
email: info@cascadiajs.com
description: > # this means to ignore newlines until "baseurl:"
  CascadiaFest is a three-day, community-driven conference on the cutting
  edge of JavaScript and CSS. Browser, server, OS – we cover it all.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://news.cascadiafest.org" # the base hostname & protocol for your site
twitter_username: cascadiajs
github_username:  cascadiajs

permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
